"""logins

Revision ID: 1eec94e3a38d
Revises: cd5ad885939c
Create Date: 2018-05-03 12:53:16.191539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eec94e3a38d'
down_revision = 'cd5ad885939c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['editors.id'], name=op.f('fk_logins_editor_id_editors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logins'))
    )
    with op.batch_alter_table(u'editors', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))

    op.drop_table('logins')
    # ### end Alembic commands ###
