"""2

Revision ID: 267a21dce715
Revises: 7500806ebff3
Create Date: 2018-05-02 13:23:26.349579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267a21dce715'
down_revision = '7500806ebff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_blogpost_editor_id_editors'), 'editors', ['editor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_blogpost_editor_id_editors'), type_='foreignkey')
        batch_op.drop_column('editor_id')

    # ### end Alembic commands ###
