"""editor username added

Revision ID: 54ff5f59f65c
Revises: 267a21dce715
Create Date: 2018-05-02 17:02:33.413500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ff5f59f65c'
down_revision = '267a21dce715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_editors_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_editors_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
