"""empty message

Revision ID: 5db3e0b8f801
Revises: 
Create Date: 2018-05-02 10:59:11.224738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db3e0b8f801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_editors_name'), 'editors', ['name'], unique=True)
    op.create_index(op.f('ix_editors_password'), 'editors', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editors_password'), table_name='editors')
    op.drop_index(op.f('ix_editors_name'), table_name='editors')
    # ### end Alembic commands ###
