"""last_seen correct

Revision ID: cd5ad885939c
Revises: d231c0ea63c8
Create Date: 2018-05-03 12:36:55.584440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5ad885939c'
down_revision = 'd231c0ea63c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('blogpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
